<?php
/*
 * citeproc-php
 *
 * @link        http://github.com/seboettg/citeproc-php for the source repository
 * @copyright   Copyright (c) 2016 Sebastian Böttger.
 * @license     https://opensource.org/licenses/MIT
 */

namespace Seboettg\CiteProc\Locale;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 13:29:49.
 */
class LocaleTest extends TestCase
{
    /**
     * @var Locale
     */
    protected $object;

    public function testFilterTerms()
    {
        $a1 = $this->object->filter("terms", "no date");
        $a2 = $this->object->filter("terms", "no date", "short");
        static::assertEquals("ohne Datum", $a1->{'single'});
        static::assertEquals("o. J.", $a2->{'single'});
    }

    protected function setUp()
    {
        $this->object = new Locale("de-DE");
    }
}
