<?php

namespace Seboettg\CiteProc\Rendering;


use Seboettg\CiteProc\Locale\Locale;
use Seboettg\CiteProc\CiteProc;
use Seboettg\CiteProc\Context;

class NumberTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $context = new Context();
        $context->setLocale(new Locale("en-GB"));
        CiteProc::setContext($context);
    }

    public function testRenderOrdinal()
    {

        $number = new Number(new \SimpleXMLElement('<number variable="edition" form="ordinal"/>'));
        $data = json_decode("{\"title\": \"Ein Buch\", \"edition\": 3}");

        $this->assertEquals("3rd", $number->render($data));
    }

    public function testRenderLongOrdinal()
    {
        $number = new Number(new \SimpleXMLElement('<number variable="edition" form="long-ordinal"/>'));
        $data = json_decode("{\"title\": \"Ein Buch\", \"edition\": 3}");

        $this->assertEquals("third", $number->render($data));
    }

    public function testRenderRoman()
    {
        $number = new Number(new \SimpleXMLElement('<number variable="edition" form="roman"/>'));
        $data = json_decode("{\"title\": \"Ein Buch\", \"edition\": 4}");

        $this->assertEquals("iv", $number->render($data));

        $data = json_decode("{\"title\": \"Ein Buch\", \"edition\": 1678}");
        $this->assertEquals("mdclxxviii", $number->render($data));
    }

    public function testRenderAffixesTextCase()
    {
        $number = new Number(new \SimpleXMLElement('<number variable="edition" form="roman" text-case="uppercase" prefix="[" suffix="]"/>'));
        $data = json_decode("{\"title\": \"Ein Buch\", \"edition\": 16}");
        $this->assertEquals("[XVI]", $number->render($data));
    }
}
