<?php
/**
 * citeproc-php
 *
 * @link        http://github.com/seboettg/citeproc-php for the source repository
 * @copyright   Copyright (c) 2016 Sebastian Böttger.
 * @license     https://opensource.org/licenses/MIT
 */

namespace Seboettg\CiteProc\Rendering\Names;

use Seboettg\CiteProc\CiteProc;
use Seboettg\CiteProc\Context;
use Seboettg\CiteProc\Locale\Locale;
use Seboettg\CiteProc\Rendering\Group;
use Seboettg\CiteProc\Rendering\Name\Names;
use Seboettg\CiteProc\TestSuiteTestCaseTrait;
use Seboettg\CiteProc\TestSuiteTests;

class NamesTest extends \PHPUnit_Framework_TestCase implements TestSuiteTests
{

    use TestSuiteTestCaseTrait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $context = new Context();
        $context->setLocale(new Locale("de-DE"));
        CiteProc::setContext($context);
    }

    public function testRenderSubstitute()
    {
        $this->_testRenderTestSuite("names_substitute");
    }


    public function testEditorTranslator()
    {
        $this->_testRenderTestSuite("name_EditorTranslatorBoth");
    }

    public function testEtAl()
    {
        $this->_testRenderTestSuite("name_EtAl");
    }

    public function testSubstitute()
    {
        $this->_testRenderTestSuite("name_substitute");
    }

    public function testDelimiter()
    {
        $this->_testRenderTestSuite("name_Delimiter");
    }

    public function testNameAttrAnd()
    {
        //$this->_testRenderTestSuite("nameattr_And");
        $this->_testRenderTestSuite("nameattr_And");
    }

    public function testNameAttrDelimiterPrecedesEtAl()
    {
        $this->_testRenderTestSuite("nameattr_DelimiterPrecedesEtAl");
    }

    public function testNameAttrDelimiterPrecedesLast()
    {
        $this->_testRenderTestSuite("nameattr_DelimiterPrecedesLast");
    }

    public function testNameAttrEtAlMin()
    {
        $this->_testRenderTestSuite("nameattr_EtAlMin");
    }

    public function testNameAttrEtAlUseFirst()
    {
        $this->_testRenderTestSuite("nameattr_EtAlUseFirst");
    }

    public function testNameAttrInitializeWith()
    {
        $this->_testRenderTestSuite("nameattr_InitializeWith");
    }

    public function testRenderTestSuite()
    {
    }
}
