<?php

namespace Seboettg\CiteProc\Locale;
use Seboettg\CiteProc\Util\Factory;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 13:29:49.
 */
class LocaleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Locale
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new Locale("de-DE");
    }

    public function testFilterTerms()
    {
        $a1 = $this->object->filter("terms", "no date");
        $a2 = $this->object->filter("terms", "no date", "short");
        $this->assertEquals("ohne Datum", $a1->{'single'});
        $this->assertEquals("o. J.", $a2->{'single'});
    }


}
