<?php
/**
 * citeproc-php
 *
 * @link        http://github.com/seboettg/citeproc-php for the source repository
 * @copyright   Copyright (c) 2016 Sebastian Böttger.
 * @license     https://opensource.org/licenses/MIT
 */

namespace Seboettg\CiteProc\Styles;


use Seboettg\CiteProc\TestSuiteTestCaseTrait;

class AffixesTest extends \PHPUnit_Framework_TestCase
{
    use TestSuiteTestCaseTrait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testRenderTestSuite()
    {
        $this->_testRenderTestSuite('affix_');
    }
}
